# 配置中心
nacos:
  config:
    bootstrap:
      enable: true
      log-enable: true
    server-addr: 39.103.159.204:8848
    data-id: dev
    group: DEFAULT_GROUP
    type: yaml
    max-retry: 10
    auto-refresh: true
    config-retry-time: 1800
    config-long-poll-timeout: 46000

log4j2-nacos:
  config:
    server-addr: 39.103.159.204:8848
    data-id: test-log4j
    group: DEFAULT_GROUP


server:
  port: 9090
